[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install] 
cmds = [
  "npm install",
  "cd apps/frontend && npm install"
]

[phases.build]
cmds = ["cd apps/frontend && npm run build"]

[start]
cmd = "cd apps/frontend && npm start"