# File: coolify-deployment.yaml
# Configuration for Coolify deployment

# Frontend Application Configuration
frontend:
  name: "erp-frontend"
  git_repository: "https://github.com/yourusername/erp-system"
  git_branch: "main"
  build_pack: "dockerfile"
  base_directory: "apps/frontend"
  dockerfile_path: "apps/frontend/Dockerfile.production"
  ports_exposes: "3000"
  health_check_path: "/api/health"
  restart_policy: "unless-stopped"
  
  # Domain Configuration
  domains:
    - "erp.sbrosenterpriseerp.com"
  
  # Environment Variables
  environment_variables:
    - name: "NODE_ENV"
      value: "production"
      is_build_variable: false
    - name: "NEXT_PUBLIC_FRONTEND_URL"
      value: "https://erp.sbrosenterpriseerp.com"
      is_build_variable: true
    - name: "NEXT_PUBLIC_API_URL"
      value: "https://api.sbrosenterpriseerp.com"
      is_build_variable: true
    - name: "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
      value: "pk_test_dHJ1c3RlZC1kdWNrbGluZy00My5jbGVyay5hY2NvdW50cy5kZXYk"
      is_build_variable: true
    - name: "CLERK_SECRET_KEY"
      value: "sk_test_TsgGRcqT8xXMBwnKthRw6tQz3tOVxWJYuYaCNRHzxl"
      is_build_variable: true
    - name: "DATABASE_URL"
      value: "postgresql://sbrosdb_owner:npg_rp6hNKdWEk0c@ep-rapid-mountain-a1y4lbio-pooler.ap-southeast-1.aws.neon.tech/sbrosdb?sslmode=require&channel_binding=require"
      is_build_variable: true
    - 
  
  # Build Commands
  build_command: "npm run build:frontend"
  install_command: "npm ci"
  
  # Resource Limits
  resources:
    memory: "2GB"
    cpu: "1"

# Backend Application Configuration
backend:
  name: "erp-backend"
  git_repository: "https://github.com/AnanthaRuban-K/erp-system.git"
  git_branch: "main"
  build_pack: "dockerfile"
  base_directory: "apps/backend"
  dockerfile_path: "apps/backend/Dockerfile.production"
  ports_exposes: "3001"
  health_check_path: "/health"
  restart_policy: "unless-stopped"
  
  # Domain Configuration
  domains:
    - "api.sbrosenterpriseerp.com"
  
  # Environment Variables
  environment_variables:
    - name: "NODE_ENV"
      value: "production"
      is_build_variable: false
    - name: "PORT"
      value: "3001"
      is_build_variable: false
    - name: "HOST"
      value: "0.0.0.0"
      is_build_variable: false
    - name: "FRONTEND_URL"
      value: "https://erp.sbrosenterpriseerp.com"
      is_build_variable: false
    - name: "API_URL"
      value: "https://api.sbrosenterpriseerp.com"
      is_build_variable: false
    - name: "DATABASE_URL"
      value: "postgresql://sbrosdb_owner:npg_rp6hNKdWEk0c@ep-rapid-mountain-a1y4lbio-pooler.ap-southeast-1.aws.neon.tech/sbrosdb?sslmode=require&channel_binding=require"
      is_build_variable: true
    - name: "CLERK_SECRET_KEY"
      value: "sk_test_TsgGRcqT8xXMBwnKthRw6tQz3tOVxWJYuYaCNRHzxl"
      is_build_variable: false
    - name: "CLERK_PUBLISHABLE_KEY"
      value: "pk_test_dHJ1c3RlZC1kdWNrbGluZy00My5jbGVyay5hY2NvdW50cy5kZXYk"
      is_build_variable: false
    - 
  
  # Build Commands
  build_command: "npm run build:backend"
  install_command: "npm ci"
  
  # Resource Limits
  resources:
    memory: "2GB"
    cpu: "1"

# Database Configuration (External - Neon PostgreSQL)
database:
  type: "external"
  provider: "neon"
  url: "postgresql://sbrosdb_owner:npg_rp6hNKdWEk0c@ep-rapid-mountain-a1y4lbio-pooler.ap-southeast-1.aws.neon.tech/sbrosdb?sslmode=require&channel_binding=require"
  
# Redis Configuration (External - Upstash)
